### ISSUE TITLE
[BUG] Stuck in black screen

### ISSUE THREAD

**Issue by Sandfire5618** [Goobwabber/MultiplayerExtensions#92]
**Your Platform**
Steam with Oculus Rift S

**Describe the bug**
Whenever I am in a multiplayer lobby and we are about to play a song, I get stuck in complete darkness. Not even a "Waiting for players" sign appears. The game just freezes right there. This even happens with OST songs. I have all the required mods installed and even checked to make sure they are up to date.

**To Reproduce**

1. Go into a multiplayer lobby
2. We all pick a song
3. We all click 'Ready'
4. We exit the lobby and are on our way to play the song
5. All my friends load in but I get stick in blackness. Notn even "Waiting for other players" shows up

**Expected behavior**
Obviously I expected to be loaded into the song like everyone else.

**Log**
I would upload the file but it keeps saying it is too big.

**Screenshots/Video**

**Additional context**

**Comment by A-plou** [comment]
I got stuck in that same black screen, but I was in solo, I did fix the issue with just restarting beat saber and not go on my steamVR menu while the countdown is there. After That I never got that problem

**Comment by xTrapLordx** [comment]
A friend and I have a similar problem. When we start a map, I (the host) get the "Waiting for other players" screen, while my friend gets softlocked in a blackscreen. A few seconds later I get to the standard map layout, but there is no music neither are blocks coming. I can't end the game and need to restart the game. My friend won't get kicked out the lobby even after I closed it due to restarting the game.

I would be really grateful if you could fix this problem.
